### ISSUE TITLE
Could not find a version that satisfies the requirement gemini==1.0.6

### ISSUE THREAD

**Issue by ToanPV90** [liamhartley/cryptotradingbot#1]
While installing packages in requirements.txt, I get the error: 
ERROR: Could not find a version that satisfies the requirement gemini==1.0.6
Could you help me resolve this error? Thank you.

**Comment by liamhartley** [comment]
I'll take a look at this for you. Just comment out the line and pip install this repo to get started:
https://github.com/liamhartley/Gemini

**Comment by liamhartley** [comment]
Hi - I've updated the requirements to run the correct installation command now:

`git+git://github.com/liamhartley/Gemini.git
`

I've also updated the README with clearer instructions on how to get started. Let me know if you need any more help with this @ToanPV90
