### ISSUE TITLE
Unable to import pandas_datareader

### ISSUE THREAD

**Issue by Sobutster** [liamhartley/cryptotradingbot#5]
Hi there!
First of all i would like to thank you for your contribution and sharing Your knowledge!

I am facing problem which is probably a rooky mistake:

`D:\cryptotradingbot-master\venv\lib\site-packages\gemini\empyrical\utils.py:32: UserWarning: Unable to import pandas_datareader. Suppressing import error and continuing. All data reading functionality will raise errors; but has been deprecated and will be removed in a later version.
  warnings.warn(msg)
Warning: Pair was converted to USDT_BTC
D:\cryptotradingbot-master\venv\lib\site-packages\gemini\empyrical\stats.py:701: RuntimeWarning: invalid value encountered in true_divide
  np.divide(
D:\cryptotradingbot-master\venv\lib\site-packages\gemini\empyrical\stats.py:790: RuntimeWarning: invalid value encountered in true_divide
  np.divide(average_annual_return, annualized_downside_risk, out=out)
D:\cryptotradingbot-master\venv\lib\site-packages\gemini\empyrical\stats.py:1369: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  returns = returns[:, np.newaxis]
D:\cryptotradingbot-master\venv\lib\site-packages\gemini\empyrical\stats.py:1372: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  factor_returns = factor_returns[:, np.newaxis]`

I tried upgrades and downgrades of pandas/numpy nothing helped
Any hint is gold for me.
Looking forward for Yout help

**Comment by liamhartley** [comment]
Have you got data in your data frames? It looks like it's struggling to to a division which may be due to some zeroes or nulls?

Also if you have a copy of your script on a branch somewhere that will help debug this.

**Comment by liamhartley** [comment]
Also make sure that you've got Gemini installed correctly with `pip freeze`

**Comment by Sobutster** [comment]
Hi again.

I must have done some mess with df. Started from scratch and now i am step further.
Thanks for help and understanding newbie knowledge lvl :D

ps. Ive created a branch if You find some time to help would be nice.(cause already i have new problem it doesnt show strategy and statistics :D)

**Comment by liamhartley** [comment]
What's the output when you run your strategy?

**Comment by Sobutster** [comment]
[Nowy dokument tekstowy.txt](https://github.com/liamhartley/cryptotradingbot/files/6663768/Nowy.dokument.tekstowy.txt)

**Comment by Sobutster** [comment]
Problem solved!  😁 Thanks a lot.

**Comment by liamhartley** [comment]
No problem! Good luck and hope it goes well
